### ISSUE TITLE
Obsidian v1.0 compatibility

### ISSUE THREAD

**Issue by cweekly** [cobalamin/obsidian-remarkable#9]
It seems this plugin isn't yet compatible with Obsidian v1.0.

It isn't visible in the community plugins search,
and trying via BRAT triggers an error:
"The release is not complete and cannot be download. main.js is missing from the Release".

Please confirm that it's not just me, and what version of Obsidian is supported. 
Thanks!

**Comment by cweekly** [comment]
PS I'm not equipped to contribute a PR, but I'd be happy to help debug / validate fixes. 
Thanks for any response and efforts here. 
Per recen HN thread I think there's a lot of interest in bridging the rm2 -> obd world and this plugin could be instrumental for that.

**Comment by cobalamin** [comment]
Hi, thanks for your interest! I hadn't updated to Obsidian 1.0, I can confirm that the BRAT install process doesn't work. I found a small incompatibility in the release structure, which I fixed in release https://github.com/cobalamin/obsidian-remarkable/releases/tag/1.1.1. It seems to install fine via BRAT now. I can't verify the full functionality with my rM at the moment, could you maybe check if it works for you as-is?

I haven't made the effort to publish it as a community plugin yet, but might take care of it on the weekend / when we're sure it works for 1.0. :)

**Comment by boomskats** [comment]
Can confirm it installs on BRAT and works as expected in v1.0 👍

**Comment by cobalamin** [comment]
Closing this for now. Please let me know if something's still not working!
